### ISSUE TITLE
Generating info.json

### ISSUE THREAD

**Issue by andre15silva** [KTH/styler#15]
Hi, I'm integrating `Styler` in `Repairnator`.

How do you generate the `real_error_dataset` directory for a given project? Is there any script? If so, could you point me to it?

Thanks!

**Comment by fermadeiral** [comment]
Hi,

> How do you generate the real_error_dataset directory for a given project? Is there any script? If so, could you point me to it?

I use [this script](https://github.com/fermadeiral/checkstylerr/blob/master/scripts/collector/collect_violations.py).

> I'm integrating Styler in Repairnator.

Nice, thanks for informing me. FYI, I have a lot of local changes, I've been working on Styler but still didn't have a good time window to be able to finish my changes and push things here, which means that the API might change in a few weeks.

**Comment by andre15silva** [comment]
> I use [this script](https://github.com/fermadeiral/checkstylerr/blob/master/scripts/collector/collect_violations.py?rgh-link-date=2021-05-04T09%3A28%3A33Z).

Thanks!

> Nice, thanks for informing me. FYI, I have a lot of local changes, I've been working on Styler but still didn't have a good time window to be able to finish my changes and push things here, which means that the API might change in a few weeks.

Ok, keep me up to date on that pls! 

I've also almost finished implementing an upload system for Styler models, so they can be reused in Repairnator. I'll open a PR here soon.

**Comment by monperrus** [comment]
> I'm integrating Styler in Repairnator.

FTR, this is https://github.com/eclipse/repairnator/issues/979

>  FYI, I have a lot of local changes,

Great, looking forward to it @fermadeiral
